name: Secure React App CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build and Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: List files
        run: ls -al
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm i

      - name: Build React App
        run: npm run build

      - name: Run npm audit
        continue-on-error: true
        run: |
          npm audit --json > audit.json
          cat audit.json

      - name: Upload Audit Report
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-report
          path: audit.json

  codeql:
    name: CodeQL Scan
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript

      - name: Autobuild
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
